namespace CopilotAgent.MultiAgent.Models;

/// <summary>
/// A decomposed execution plan generated by the orchestrator LLM.
/// Contains the work chunks and their dependency relationships.
/// </summary>
public sealed class OrchestrationPlan
{
    /// <summary>Unique identifier for this plan.</summary>
    public string PlanId { get; set; } = Guid.NewGuid().ToString();

    /// <summary>The original user task description.</summary>
    public string TaskDescription { get; set; } = string.Empty;

    /// <summary>LLM-generated summary of the plan.</summary>
    public string PlanSummary { get; set; } = string.Empty;

    /// <summary>Ordered list of work chunks in this plan.</summary>
    public List<WorkChunk> Chunks { get; set; } = new();

    /// <summary>When this plan was created.</summary>
    public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;
}